### ISSUE TITLE
不支持1.8和1.18跨服聊天吗？尝试使用时出现了报错

### ISSUE THREAD

**Issue by HansOffice** [Zaohon/ServerChat#4]
[01:01:16 INFO]: [ServerChat] 接收消息时失败，请上报mcbbs
[01:01:16 WARN]: java.io.EOFException
[01:01:16 WARN]:        at java.io.DataInputStream.readFully(Unknown Source)
[01:01:16 WARN]:        at java.io.DataInputStream.readUTF(Unknown Source)
[01:01:16 WARN]:        at java.io.DataInputStream.readUTF(Unknown Source)
[01:01:16 WARN]:        at cn.blockmc.Zao_hon.Bukkit.MessageListener.onPluginMessageReceived(MessageListener.java:36)
[01:01:16 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2129)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[01:01:16 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:01:16 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710)
[01:01:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
这是报错内容

**Comment by Zaohon** [comment]
插件是哪个版本的

**Comment by HansOffice** [comment]
插件版本在大厅1.8核心使用的是1.6.71在1.18.2生存服使用的是1.8.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zaohon/ServerChat] 不支持1.8和1.18跨服聊天吗？尝试使用时出现了报错 (Issue #4)





 
插件是哪个版本的

**Comment by Zaohon** [comment]
啊对的，1.8版本的插件是只能和1.8的插件通信的，不同大版本之间的插件互相不能通信
